### PR TITLE
Adding posture definition and clarification

### LINKED ISSUE #59: Definition for "posture" missing
The spec currently lacks a "posture" definition. Given this term can mean many things, we should explicitly define this term in the context of this specification.

The spec has definitions for "current posture" and "posture mode".

### PR DESCRIPTION
**Pull request by lauramorinigo**
Closes #59 #57 

The following tasks have been completed:

 * [ ] Modified Web platform tests (link to pull request)

Implementation commitment:

 * [ ] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=) 
 * Gecko - Waiting on [standards position](https://github.com/mozilla/standards-positions/issues/210) before committing.
 * WebKit - Not participating in this working group.

### CODE REVIEW

**Comment by darktears** [comment]
LGTM

**Comment by kenchris** [comment]
LGTM but there is a build failure, I am rerunning

**Comment by anssiko** [comment]
@xfq can you fix Travis CI for this spec? It seems at least env in https://github.com/w3c/device-posture/blob/gh-pages/.travis.yml does not match this spec.

Meanwhile, @kenchris feel feel to merge if you’ve tested in your local env with no errors.

**Comment by xfq** [comment]
This PR only changes the README, so I think we can merge it.

In the meantime, I will see if we can use GitHub Actions to build/validate/publish this spec.

**Pull request merged**
