### PR TITLE
Rename word "mode" in the posture definition to "type".

### LINKED ISSUE #64: Rename "posture modes" to "posture types"
As the DevicePosture interface has now a member called `type`, we may want to rename [posture modes](https://w3c.github.io/device-posture/#posture-modes) to "posture types" for consistency.
What do you folks think about it?

```idl
interface DevicePosture : EventTarget {
  readonly attribute DevicePostureType type;
  ...
};
```

### PR DESCRIPTION
**Pull request by darktears**
Closes  #64

***
<a href="https://pr-preview.s3.amazonaws.com/darktears/device-posture/pull/68.html" title="Last updated on Apr 22, 2021, 7:41 PM UTC (db129ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/device-posture/68/fb2d39d...darktears:db129ee.html" title="Last updated on Apr 22, 2021, 7:41 PM UTC (db129ee)">Diff</a>

### CODE REVIEW

**Comment by darktears** [comment]
@anssiko @kenchris @beaufortfrancois

**Review by kenchris — APPROVED** [review]

**Comment by darktears** [comment]
@anssiko feel free to merge when you want. It's a rather simple fix.

**Comment by anssiko** [comment]
Generally I give the editors a mandate to merge PRs that have received adequate review.

@kenchris

**Comment by darktears** [comment]
@kenchris is too nice, he wants you to click!

**Pull request merged**
